server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

  # File upload configuration for tutor verification documents
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  cache:
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h

jwt:
  secret: ${JWT_SECRET}
  access-token-exp-min: 60
  issuer: learnverse-api

# Custom file storage configuration
app:
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}

  admin:
    email: ${ADMIN_EMAIL:admin@learnverse.com}
    password: ${ADMIN_PASSWORD:admin@123}
    name: ${ADMIN_NAME:System Administrator}

logging:
  level:
    org.springframework.security: DEBUG

gemini:
  api:
    key: ${GEMINI_API_KEY}
    model: "gemini-2.5-pro"
    base-url: "https://generativelanguage.googleapis.com/v1beta"

learning-assistant:
  name: "LearnVerse AI"
  personality: "encouraging, supportive, student-focused, practical"
  max-tokens: 1500
  temperature: 0.8


