server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

  # File upload configuration for tutor verification documents
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  cache:
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h

jwt:
  secret: ${JWT_SECRET}
  access-token-exp-min: 60
  issuer: learnverse-api

# Custom file storage configuration
app:
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}

logging:
  level:
    org.springframework.security: DEBUG
