package com.example.learnverse.enrollment.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Document(collection = "course_enrollments")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CourseEnrollment {

    @Id
    private String id;

    // Core Information
    private String userId;
    private String userName; // For quick access
    private String activityId;
    private String activityTitle; // For quick access
    private String tutorId;
    private String tutorName; // For quick access

    // Enrollment Details
    private LocalDateTime enrolledAt;
    private EnrollmentStatus status; // ENROLLED, IN_PROGRESS, COMPLETED, DROPPED, PAUSED
    private Double progressPercentage; // 0.0 to 100.0

    // Learning Progress
    private Integer sessionsAttended;
    private Integer totalSessions;
    private LocalDateTime lastActivityDate;
    private LocalDateTime completedAt;

    // Performance Metrics
    private Double averageRating; // Student's rating of the course
    private String feedback; // Student feedback
    private Integer studyHoursSpent;

    // AI Insights (Generated by chatbot)
    private String learningPattern; // "Consistent", "Irregular", "Fast Learner", etc.
    private String strugglingAreas; // Topics where student needs help
    private String strongAreas; // Topics student excels at
    private String nextRecommendations; // AI suggestions for next steps

    // Timestamps
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
